using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Web.Http;
using System.Web.Http.SelfHost;
using System.Net.Http.Headers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Coevolution.Models;

using Coevolution.Controllers;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {

        private HttpSelfHostConfiguration config;
        private HttpSelfHostServer server;
        private HttpClient client;

        private String address = "http://localhost:55426";

        /* This test suite tests all supported API calls provided by Items and Labels Controller.
         * Two different testing methodologies are used, one which is present
         * in the Search tests, the other which is present in all others.
         * For the search tests, no items are explicitly inserted, instead, checks are made
         * based on objects created by the seed. Return requests are handled by Json deserialisation.
         * These tests also work under the assumption that the database is clean.
         * For all other tests, no assumptions are made regarding the database state, and instead,
         * items are inserted and checked for. Return requests are handled by Regex on the response body.
         * Both methods of testing work, and future tests can be added based on developer preference.
         * Methods which are not tests are helper methods for them, as all tests follow the make request ->
         * check request pattern and hence there is potential for repeated code.
         * */

        [TestInitialize]
        public void Setup()
        {
            // Remove all items that arent't generated by the seed, wiping the database of any items added during testing.
            using (var db = new ModelContext())
            {
                db.Items.RemoveRange(db.Items.Where(x => x.Id > 8));
                db.Labels.RemoveRange(db.Labels.Where(x => x.Id > 6));
                db.Notes.RemoveRange(db.Notes.Where(x => x.Id > 6));
                db.SaveChanges();
            }
            // Setup config/server/client
            var two = typeof(ItemsController).Assembly;
            config = new HttpSelfHostConfiguration(address);
            config.MapHttpAttributeRoutes();
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
            server = new HttpSelfHostServer(config);
            client = new HttpClient();
            server.OpenAsync().Wait();
        }

        [TestCleanup]
        public void TearDown()
        {
            server.CloseAsync().Wait();
            client.Dispose();
            server.Dispose();
        }

        [TestMethod, Description("Test the basic post case for an item, by creating one and checking the returned item matches.")]
        public void TestPost()
        {
            // Create DtoItem as json
            var requestJson = "{\"Type\": \"node\",\"key\":\"Object to created by TestPost!\"}";

            // Make post item request
            HttpRequestMessage request = PostItem(requestJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Check fields match submitted item
                MatchOnce(result, "\"Id\":\\s*[0-9]+");
                MatchOnce(result, "\"Key\":\\s*\"Object to created by TestPost!\"");
                MatchOnce(result, "\"Type\":\\s*\"node\"");
                MatchOnce(result, "\"Parent\":\\s*null");
                MatchOnce(result, "\"Deleted\":\\s*false");
                MatchOnce(result, "\"Labels\":\\s*\\[\\]");
                MatchOnce(result, "\"Notes\":\\s*\\[\\]");
                MatchOnce(result, "\"LeafChildren\":\\s*\\[\\]");
                MatchOnce(result, "\"NodeChildren\":\\s*\\[\\]");
                MatchOnce(result, "\"CreatedOn\":\\s*\"[0123456789\\-T:]+\"");
                MatchOnce(result, "\"UpdatedOn\":\\s*\"[0123456789\\-T:]+\"");
            }

        }

        [TestMethod, Description("Test the basic post case for an label, by creating one and checking the returned label matches.")]
        public void TestPostLabel()
        {
            // Create DtoLabel as json
            var requestJson = "{\"Content\": \"Label to be created by TestPostLabel!\"}";

            // Make post label request
            HttpRequestMessage request = PostLabel(requestJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Check fields match submitted label
                MatchOnce(result, "\"Id\":\\s*[0-9]+");
                MatchOnce(result, "\"Content\":\\s*\"Label to be created by TestPostLabel!\"");
            }
        }

        [TestMethod, Description("Test getting all labels, by adding a label, getting all labels, and ensuring the label added is present.")]
        public void TestGetAllLabels()
        {
            int labelID;

            // Create DtoLabel as json
            var requestJson = "{\"Content\": \"Label to be created by TestGetAllLabels!\"}";

            // Make post label request
            HttpRequestMessage request = PostLabel(requestJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Extract the label's Id from the response body
                labelID = int.Parse(Regex.Match(result, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Make get all labels request (no id specified)
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/labels/");

            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);

                // Check an array of labels is returned, and check the added label is present
                MatchOnce(result, "^\\[");
                MatchOnce(result, "\"Id\":\\s*" + labelID);
                Assert.IsTrue(1 < Regex.Matches(result, "\"Items\":\\s*\\[\\]").Count);
                MatchOnce(result, "\"Content\":\\s*\"Label to be created by TestGetAllLabels!\"");
                MatchOnce(result, "\\]$");

            }

        }

        [TestMethod, Description("Test label deletion, by adding a label, removing it by Id, and checking it is deleted.")]
        public void TestDeleteLabel()
        {
            int labelID;

            // Create DtoLabel as json
            var requestJson = "{\"Content\": \"Label to be created by TestGetAllLabels!\"}";

            // Make post label request
            HttpRequestMessage request = PostLabel(requestJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Extract the label's Id from the response body
                labelID = int.Parse(Regex.Match(result, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Make delete label request using Id
            request = new HttpRequestMessage(HttpMethod.Delete, address + "/api/labels/" + labelID);

            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
            }

            // Make get all labels request (no id specified)
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/labels/");

            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Check that the deleted label's Id is not present
                Regex label = new Regex("\"Id\":\\s*" + labelID);
                Assert.IsFalse(label.Match(result).Success);
            }
        }

        [TestMethod, Description("Test post when creating parent-child relationship, and ensure this shows.")]
        public void TestPostChild()
        {
            int parentId;
            int childId;

            // Create DtoItem as json, to act as parent
            var parentJson = "{\"Type\": \"node\",\"key\":\"Parent to created by TestPostChild!\"}";

            String firstResult;

            // Create parent

            // Make post item request
            HttpRequestMessage request = PostItem(parentJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                firstResult = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Extract the parent's Id from the response body
                parentId = int.Parse(Regex.Match(firstResult, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Create DtoItem as json, to act as child
            var childJson = "{\"Type\": \"node\",\"key\":\"Child to created by TestPostChild!\",\"Parent\":" + parentId + "}";

            // Create child

            // Make post item request
            request = PostItem(childJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var secondResult = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);
                // Ensure parent relationship is shown in the child Dto
                MatchOnce(secondResult, "\"Parent\":\\s*" + parentId);

                // Extract the parent's Id from the response body
                childId = int.Parse(Regex.Match(secondResult, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Check parent has child

            // Make get item request using parent's Id
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + parentId);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var thirdResult = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);

                // Extract children list from json list of children (ew)
                Regex nodeChildrenRegex = new Regex("\"NodeChildren\":\\s*\\[(\\{[^\\}]*\\})\\]");
                var child = nodeChildrenRegex.Match(thirdResult).Groups[1].Value;

                // Check child's Id is present
                MatchOnce(child, "\"Id\":\\s*" + childId);
            }

            // Check child doesn't show in top level.

            // Make get item request with no Id (all top level items)
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/");
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var fourthResult = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);

                // Check child's Id is not present
                Regex regChild = new Regex("\"Id\":\\s*" + childId);
                Assert.IsFalse(regChild.Match(fourthResult).Success);

            }
        }

        [TestMethod, Description("Test getting a single Item's information, by adding one and making a request for it.")]
        public void TestGetOne()
        {
            int createdId;

            // Create DtoItem as json
            var jsonString = "{\"Type\": \"node\",\"key\":\"Object to created by TestGetOne!\"}";

            String firstResult;

            // Make post item request
            HttpRequestMessage request = PostItem(jsonString);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                firstResult = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Extract the item's Id from the response body
                createdId = int.Parse(Regex.Match(firstResult, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Make get item request for that item
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + createdId);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var secondResult = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);

                // Ensure extracted id matches in item returned by request
                Assert.AreEqual(firstResult, secondResult);
            }

        }

        [TestMethod, Description("Test getting all Items by adding an item, making a request for all items, and checking it's there.")]
        public void TestGetAll()
        {
            int createdId;

            // Create DtoItem as json
            var jsonString = "{\"Type\": \"node\",\"key\":\"Object to created by TestGetAll!\"}";

            // Make post item request
            HttpRequestMessage request = PostItem(jsonString);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Extract the item's Id from the response body
                createdId = int.Parse(Regex.Match(result, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Make get all items request (no id specified)
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/");

            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var result = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);

                // Check an array of items is returned, and check the added item is present
                MatchOnce(result, "^\\[");
                MatchOnce(result, "\"Id\":\\s*" + createdId);
                MatchOnce(result, "\"Key\":\\s*\"Object to created by TestGetAll!\"");
                MatchOnce(result, "\\]$");

            }

        }

        [TestMethod, Description("Test the basic put case for an item, by creating one, updating it, and checking the update shows.")]
        public void TestPut()
        {
            int createdId;

            // Create DtoItem as json
            var jsonString = "{\"Type\": \"node\",\"key\":\"Object to created by TestPut!\"}";

            String firstResult;

            // Make post item request
            HttpRequestMessage request = PostItem(jsonString);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                firstResult = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Extract the item's Id from the response body
                createdId = int.Parse(Regex.Match(firstResult, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Change the json's content (i.e, replace the key)
            Regex reg = new Regex("Object to created by TestPut!");
            var newJson = reg.Replace(firstResult, "Object to edited by TestPut!");

            // Make put item request, with this updated item
            request = PutItem(createdId, newJson);
            // Ensure request was OK
            Assert.AreEqual(HttpStatusCode.OK, GetRequestStatus(request));

            // Make get item request using the item's Id
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + createdId);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var secondResult = task.Result;

                // Ensure request was OK
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
                // Ensure that the returned item reflects the change
                Regex reg2 = new Regex("Object to edited by TestPut!");
                Assert.IsTrue(reg2.Match(secondResult).Success);
            }

        }

        [TestMethod, Description("Test deletion of an item, ensure that it can still be found using the correct paramaters, and ensure deletion interacts with children correctly.")]
        public void TestDelete()
        {
            int parentId;
            int childId;

            // Create DtoItem as json, to act as parent
            var parentJson = "{\"Type\": \"node\",\"key\":\"Parent to created by TestDelete!\"}";

            String firstResult;

            // Posting the main item
            HttpRequestMessage request = PostItem(parentJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                firstResult = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);

                // Extract the parent's Id from the response body
                parentId = int.Parse(Regex.Match(firstResult, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Create DtoItem as json, to act as child
            var childJson = "{\"Type\": \"node\",\"key\":\"Child to created by TestDelete!\",\"Parent\":" + parentId + "}";

            // Posting the child item
            request = PostItem(childJson);
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var secondResult = task.Result;

                // Ensure status code reflects creation
                Assert.AreEqual(HttpStatusCode.Created, response.StatusCode);
                // Ensure the child has the parent specified and correct
                MatchOnce(secondResult, "\"Parent\":\\s*" + parentId);

                // Extract the child's Id from the response body
                childId = int.Parse(Regex.Match(secondResult, "\"Id\":\\s*([0-9]+)").Groups[1].Value);
            }

            // Getting the main item should tell us it is there
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + parentId);
            Assert.AreEqual(HttpStatusCode.OK, GetRequestStatus(request));

            // Delete the main item
            request = new HttpRequestMessage(HttpMethod.Delete, address + "/api/items/" + parentId);
            Assert.AreEqual(HttpStatusCode.OK, GetRequestStatus(request));

            // Getting the main item should tell us it isn't there
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + parentId);
            Assert.AreEqual(HttpStatusCode.NotFound, GetRequestStatus(request));

            // Getting the child item should tell us it isn't there
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + childId);
            Assert.AreEqual(HttpStatusCode.NotFound, GetRequestStatus(request));

            // Getting the main item should tell us it is there if we ask for deleted items
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + parentId + "?showDeleted=true");
            Assert.AreEqual(HttpStatusCode.OK, GetRequestStatus(request));

            // Getting the child item should tell us it is there if we ask for deleted items
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/" + childId + "?showDeleted=true");
            Assert.AreEqual(HttpStatusCode.OK, GetRequestStatus(request));

            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/");

            // Getting everything should tell us the main item isn't there
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var thirdResult = task.Result;

                // Ensure parent it not there
                Regex regParent = new Regex("\"Id\":\\s*" + parentId);
                Assert.IsFalse(regParent.Match(thirdResult).Success);

                // Ensure child is not there
                Regex regChild = new Regex("\"Id\":\\s*" + childId);
                Assert.IsFalse(regChild.Match(thirdResult).Success);

            }

            // Getting everything should tell us the main item is there if we ask for deleted items
            request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items?showDeleted=true");

            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                var fourthResult = task.Result;

                Regex reg = new Regex("\"Id\":\\s*" + parentId);
                Assert.IsTrue(reg.Match(fourthResult).Success);

            }
        }

        [TestMethod, Description("Tests 404 cases for Item get, put and delete.")]
        public void TestNotFound()
        {
            // Get item 0 (which will never exist)
            var request = new HttpRequestMessage(HttpMethod.Get, address + "/api/items/0");
            Assert.AreEqual(HttpStatusCode.NotFound, GetRequestStatus(request));

            // Put to item 0 (which doesn't exist)
            request = PutItem(0, "{\"id\":\"0\", \"Type\":\"node\"}");
            Assert.AreEqual(HttpStatusCode.NotFound, GetRequestStatus(request));

            // Delete to item 0 (which doesn't exist)
            request = new HttpRequestMessage(HttpMethod.Delete, address + "/api/items/0");
            Assert.AreEqual(HttpStatusCode.NotFound, GetRequestStatus(request));
        }

        [TestMethod, Description("Tests cases where the provided Dto is not valid for put and post.")]
        public void TestBadRequest()
        {

            // Ensure empty body fails for post
            var request = PostItem("");
            Assert.AreEqual(HttpStatusCode.BadRequest, GetRequestStatus(request));

            // Ensure missing fields fails for post, key is required
            request = PostItem("{\"Type\":\"node\"}");
            Assert.AreEqual(HttpStatusCode.BadRequest, GetRequestStatus(request));

            // Ensure missing fields fails for post, type is required
            request = PostItem("{\"key\":\"this should fail\"}");
            Assert.AreEqual(HttpStatusCode.BadRequest, GetRequestStatus(request));

            // Ensure empty string fails for put
            request = PutItem(0, "");
            Assert.AreEqual(HttpStatusCode.BadRequest, GetRequestStatus(request));

            // Ensure id mismatch fails for put
            request = PutItem(0, "{\"id\":3}");
            Assert.AreEqual(HttpStatusCode.BadRequest, GetRequestStatus(request));
        }



        [TestMethod, Description("Test node key search, by searching for a Node generated by the seed.")]
        public void TestSearchNodeKey()
        {

            String result;

            // Make key search request
            HttpRequestMessage request = SearchKey("Kiwibank");
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                result = task.Result;

                // Deserialise and check fields match generated Node
                var item = JsonConvert.DeserializeObject<List<DtoSearchItem>>(result)[0];
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
                Assert.AreEqual(1, item.Id);
                Assert.AreEqual(false, item.IsLeaf);
                Assert.AreEqual(null, item.Value);
                Assert.AreEqual("KiwiBank", item.Key);
                Assert.AreEqual(1, item.Path[0].Key);
            }
        }

        [TestMethod, Description("Test leaf key search, by searching for a Leaf generated by the seed.")]
        public void TestSearchLeafKey()
        {

            String result;

            // Make key search request
            HttpRequestMessage request = SearchKey("Login");
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                result = task.Result;

                // Deserialise and check fields match generated Leaf, and are presented as defined
                var item = JsonConvert.DeserializeObject<List<DtoSearchItem>>(result)[0];
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
                // Actual node id is 7, but return parent because its a leaf
                Assert.AreEqual(6, item.Id);
                Assert.AreEqual(true, item.IsLeaf);
                Assert.AreEqual("Login", item.Key);
                Assert.AreEqual("Admin", item.Value);
                // Two parents
                Assert.AreEqual(1, item.Path[0].Key);
                Assert.AreEqual(6, item.Path[1].Key);
            }
        }

        [TestMethod, Description("Test leaf value search, by searching for a Leaf generated by the seed with associated parents.")]
        public void TestSearchLeafValue()
        {

            String result;
            HttpRequestMessage request = SearchValue("testEmail");
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                result = task.Result;
                var item = JsonConvert.DeserializeObject<List<DtoSearchItem>>(result)[0];
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
                //Actual node id is 7, but return parent because its a leaf
                Assert.AreEqual(1, item.Id);
                Assert.AreEqual(true, item.IsLeaf);
                Assert.AreEqual("Email", item.Key);
                Assert.AreEqual("example@testEmail.com", item.Value);
                Assert.AreEqual(1, item.Path[0].Key);
            }
        }

        [TestMethod, Description("Test label search, by searching for a label generated by the seed with associated items.")]
        public void TestSearchLabel()
        {

            String result;
            // Make label search request
            HttpRequestMessage request = SearchLabel("bank");
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();
                result = task.Result;
                // Deserialise and check fields match the Node this label is assigned to by generation
                var items = JsonConvert.DeserializeObject<List<DtoSearchItem>>(result);
                var item = items[0];
                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
                Assert.AreEqual(3, items.Count);
                Assert.AreEqual(2, item.Id);
                Assert.AreEqual(false, item.IsLeaf);
                Assert.AreEqual(null, item.Value);
                Assert.AreEqual("ASB", item.Key);
                Assert.AreEqual(2, item.Path[0].Key);
            }
        }

        // Helper method for searching by Key
        private HttpRequestMessage SearchKey(string query)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, address + "/api/Items/Search/Key/" + query);
            return request;
        }

        // Helper method for searching by Value
        private HttpRequestMessage SearchValue(string query)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, address + "/api/Items/Search/Value/" + query);
            return request;
        }

        // Helper method for searching by Label
        private HttpRequestMessage SearchLabel(string query)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, address + "/api/Items/Search/Label/" + query);
            return request;
        }

        // Helper method for making a post to labels. Item json must be specified.
        private HttpRequestMessage PostLabel(String jsonString)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, address + "/api/labels");
            PopulateBody(request, jsonString);
            return request;
        }

        // Helper method for making a post to items. Item json must be specified.
        private HttpRequestMessage PostItem(String jsonString)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, address + "/api/items");
            PopulateBody(request, jsonString);
            return request;
        }

        // Helper method for making a put to items. Item json and Id must be specified.
        private HttpRequestMessage PutItem(int id, String jsonString)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Put, address + "/api/items/" + id);
            PopulateBody(request, jsonString);
            return request;
        }

        // Helper method for extracting the status code of a given request.
        private HttpStatusCode GetRequestStatus(HttpRequestMessage request)
        {
            using (request)
            using (HttpResponseMessage response = client.SendAsync(request).Result)
            {
                var task = response.Content.ReadAsStringAsync();
                task.Wait();

                return response.StatusCode;
            }
        }

        // Helper method for correctly wrapping json body content.
        private void PopulateBody(HttpRequestMessage request, String jsonString)
        {
            var content = new StringContent(jsonString);
            content.Headers.ContentType = new MediaTypeHeaderValue("text/json");
            request.Content = content;
            return;
        }

        // Helper method for mathing a given regex to a given phrase exactly once.
        private void MatchOnce(String phrase, String regex)
        {
            Assert.AreEqual(1, Regex.Matches(phrase, regex).Count);
        }
    }
}
